# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*' # Trigger builds on all branches

pr:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'
- task: DotNetCoreInstaller@1
  displayName: 'DotNet Core Installer'
- task: UseDotNet@2
  displayName: 'Use DotNet'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/UMN-AutoPackager/bin'
    zipAfterPublish: false
    modifyOutputPath: false
- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/UMN-AutoPackager'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/UMN-AutoPackager'
- task: CmdLine@2
  displayName: 'Run CmdLine'
  inputs:
    script: 'dir /b /s $(Build.ArtifactStagingDirectory)'
